name: Generate VP ontology documentation
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'src/ontology.ttl'
env:
  ONTOLOGY_FILE: src/ontology.ttl
  
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ontospy
        wget -O widoco.jar https://github.com/dgarijo/Widoco/releases/download/v1.4.25/widoco-1.4.25-jar-with-dependencies_JDK-17.jar
        mkdir -p docs/browse docs/tree docs/graph docs/lode

    - name: Generate docs with Widoco (LODE)
      run: |
        mkdir vpa-doc/lode/
        java -jar widoco.jar -ontFile $ONTOLOGY_FILE -outFolder vpa-doc/lode/ -getOntologyMetadata -oops -rewriteAll -webVowl
        #mv docs/lode docs/lode-tmp
        #mv docs/lode-tmp/doc docs/lode
        mv vpa-doc/lode/index-en.html vpa-doc/lode/index.html
        mv vpa-doc/lode/OOPSevaluation vpa-doc/lode/oops
        mv vpa-doc/lode/oops/oopsEval.html vpa-doc/lode/oops/index.html

    - name: Generate docs with Ontospy
      run: |
        mkdir vpa-doc/browse
        mkdir vpa-doc/tree
        mkdir vpa-doc/graph
        ontospy gendocs -o vpa-doc/browse/ --type 2 --preflabel label --nobrowser $ONTOLOGY_FILE
        ontospy gendocs -o vpa-doc/tree/ --type 4 --preflabel label --nobrowser $ONTOLOGY_FILE
        ontospy gendocs -o vpa-doc/graph/ --type 10 --preflabel label --nobrowser $ONTOLOGY_FILE
  

    - name: Commit and push
      run: |
        git config --global user.name 'Ghislain Atemezing'
        git config --global user.email 'ghislain.atemezing@gmail.com'
        git config --global remote.origin.url 'https://github.com/gatemezing/ERA-VPA_Ontology.git'
        git config --global credential.helper 'osxkeychain'
        git fetch
        #git checkout gh-pages
        #rm -rf browse tree graph lode
        #mv docs/* .
        #git add browse graph lode tree
        git add vpa-doc/lode vpa-doc/browse vpa-doc/graph
        git commit -m "Automatically generate documentation from VPA OWL ontology file using Ontospy and Widoco (lode)."
        git push || exit 0
  
    
    - uses: actions/download-artifact@v4
    - name: Display structure of downloaded files
      run: ls -R

    
