name: Generate VP ontology documentation
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'src/ontology.ttl'
env:
  ONTOLOGY_FILE: src/ontology.ttl
  
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ontospy
        wget -O widoco.jar https://linkedvocabs.org/tmp/widoco/widoco-1.4.24-jar-with-dependencies-era.jar
        java-17-widoco-1.4.17-jar-with-dependencies.jar
        mkdir -p docs/browse docs/tree docs/graph docs/lode

    - name: Generate docs with Widoco (LODE)
      run: |
        java -jar widoco.jar -ontFile $ONTOLOGY_FILE -outFolder docs/lode/ -getOntologyMetadata -oops -rewriteAll -webVowl
        mv docs/lode docs/lode-tmp
        mv docs/lode-tmp/doc docs/lode
        mv docs/lode/index-en.html docs/lode/index.html
        mv docs/lode/OOPSevaluation docs/lode/oops
        mv docs/lode/oops/oopsEval.html docs/lode/oops/index.html

    - name: Generate docs with Ontospy
      run: |
        ontospy gendocs -o docs/browse --type 2 --preflabel label --nobrowser $ONTOLOGY_FILE
        ontospy gendocs -o docs/tree --type 4 --preflabel label --nobrowser $ONTOLOGY_FILE
        ontospy gendocs -o docs/graph --type 10 --preflabel label --nobrowser $ONTOLOGY_FILE

    - name: Commit and push
      run: |
        git config --global user.name 'Ghislain Atemezing'
        git config --global user.email 'ghislain.atemezing@gmail.com'
        git fetch
        git checkout gh-pages
        rm -rf browse tree graph lode
        mv docs/* .
        git add browse graph lode tree
        git commit -m "Automatically generate documentation from EU Rail OWL ontology file using Ontospy and Widoco (lode)."
        git push || exit 0

    
